export const applications_dummy_data = [
  {
    id: 1,
    name: "John Doe",
    university: "Harvard University",
    country: "USA",
    duration: 4,
    cost: 60000,
    deadline: "2025-03-15",
    language: "English",
  },
  {
    id: 2,
    name: "Jane Smith",
    university: "University of Toronto",
    country: "Canada",
    duration: 3,
    cost: 40000,
    deadline: "2025-06-01",
    language: "English",
  },
  {
    id: 3,
    name: "Alice Johnson",
    university: "ETH Zurich",
    country: "Switzerland",
    duration: 5,
    cost: 30000,
    deadline: "2025-01-15",
    language: "English",
  },
  {
    id: 4,
    name: "David Brown",
    university: "University of Melbourne",
    country: "Australia",
    duration: 6,
    cost: 50000,
    deadline: "2025-07-12",
    language: "English",
  },
  {
    id: 5,
    name: "Emily Davis",
    university: "University of Cambridge",
    country: "UK",
    duration: 3,
    cost: 45000,
    deadline: "2025-04-30",
    language: "English",
  },
  {
    id: 6,
    name: "Liam Wilson",
    university: "Sorbonne University",
    country: "France",
    duration: 4,
    cost: 20000,
    deadline: "2025-05-20",
    language: "French",
  },
  {
    id: 7,
    name: "Olivia Martinez",
    university: "University of Tokyo",
    country: "Japan",
    duration: 2,
    cost: 35000,
    deadline: "2025-08-15",
    language: "English",
  },
  {
    id: 8,
    name: "Noah Taylor",
    university: "University of Sydney",
    country: "Australia",
    duration: 3,
    cost: 40000,
    deadline: "2025-02-28",
    language: "English",
  },
  {
    id: 9,
    name: "Sophia Thomas",
    university: "Bogazici University",
    country: "Turkey",
    duration: 5,
    cost: 15000,
    deadline: "2025-09-30",
    language: "Turkish",
  },
  {
    id: 10,
    name: "Lucas White",
    university: "McGill University",
    country: "Canada",
    duration: 4,
    cost: 50000,
    deadline: "2025-12-15",
    language: "English",
  },
  {
    id: 11,
    name: "Emma Green",
    university: "University of Oxford",
    country: "UK",
    duration: 3,
    cost: 42000,
    deadline: "2025-11-01",
    language: "English",
  },
  {
    id: 12,
    name: "James Hall",
    university: "Ludwig Maximilian University of Munich",
    country: "Germany",
    duration: 5,
    cost: 25000,
    deadline: "2025-01-10",
    language: "English",
  },
  {
    id: 13,
    name: "Amelia Young",
    university: "University of Amsterdam",
    country: "Netherlands",
    duration: 4,
    cost: 30000,
    deadline: "2025-06-15",
    language: "English",
  },
  {
    id: 14,
    name: "Henry Adams",
    university: "University of Paris",
    country: "France",
    duration: 3,
    cost: 15000,
    deadline: "2025-07-22",
    language: "French",
  },
  {
    id: 15,
    name: "Mia Turner",
    university: "Koc University",
    country: "Turkey",
    duration: 5,
    cost: 20000,
    deadline: "2025-04-01",
    language: "Turkish",
  },
  {
    id: 16,
    name: "Ethan Scott",
    university: "Stanford University",
    country: "USA",
    duration: 6,
    cost: 70000,
    deadline: "2025-02-15",
    language: "English",
  },
  {
    id: 17,
    name: "Ava King",
    university: "University of Zurich",
    country: "Switzerland",
    duration: 4,
    cost: 32000,
    deadline: "2025-03-30",
    language: "English",
  },
  {
    id: 18,
    name: "Alexander Campbell",
    university: "Technical University of Munich",
    country: "Germany",
    duration: 6,
    cost: 22000,
    deadline: "2025-09-10",
    language: "English",
  },
  {
    id: 19,
    name: "Isabella Perez",
    university: "University of Barcelona",
    country: "Spain",
    duration: 3,
    cost: 18000,
    deadline: "2025-10-15",
    language: "English",
  },
  {
    id: 20,
    name: "William Roberts",
    university: "University of Edinburgh",
    country: "UK",
    duration: 5,
    cost: 38000,
    deadline: "2025-11-25",
    language: "English",
  },
  {
    id: 21,
    name: "Charlotte Harris",
    university: "Istanbul University",
    country: "Turkey",
    duration: 4,
    cost: 10000,
    deadline: "2025-05-12",
    language: "Turkish",
  },
  {
    id: 22,
    name: "Benjamin Clark",
    university: "University of Cape Town",
    country: "South Africa",
    duration: 3,
    cost: 25000,
    deadline: "2025-07-18",
    language: "English",
  },
  {
    id: 23,
    name: "Evelyn Rodriguez",
    university: "University of Porto",
    country: "Portugal",
    duration: 2,
    cost: 12000,
    deadline: "2025-09-15",
    language: "English",
  },
  {
    id: 24,
    name: "Michael Lewis",
    university: "University of Queensland",
    country: "Australia",
    duration: 6,
    cost: 40000,
    deadline: "2025-10-20",
    language: "English",
  },
  {
    id: 25,
    name: "Abigail Walker",
    university: "University of Helsinki",
    country: "Finland",
    duration: 4,
    cost: 16000,
    deadline: "2025-03-10",
    language: "English",
  },
  {
    id: 26,
    name: "Daniel Lee",
    university: "University of Milan",
    country: "Italy",
    duration: 3,
    cost: 21000,
    deadline: "2025-06-01",
    language: "English",
  },
  {
    id: 27,
    name: "Sofia Allen",
    university: "University of Vienna",
    country: "Austria",
    duration: 5,
    cost: 30000,
    deadline: "2025-02-28",
    language: "English",
  },
  {
    id: 28,
    name: "Jackson Hill",
    university: "Ecole Polytechnique",
    country: "France",
    duration: 6,
    cost: 23000,
    deadline: "2025-08-30",
    language: "French",
  },
  {
    id: 29,
    name: "Scarlett Young",
    university: "Bogazici University",
    country: "Turkey",
    duration: 4,
    cost: 18000,
    deadline: "2025-04-20",
    language: "Turkish",
  },
  {
    id: 30,
    name: "Sebastian Adams",
    university: "University of Copenhagen",
    country: "Denmark",
    duration: 3,
    cost: 25000,
    deadline: "2025-12-01",
    language: "English",
  },
  {
    id: 31,
    name: "Grace Nelson",
    university: "National University of Singapore",
    country: "Singapore",
    duration: 5,
    cost: 35000,
    deadline: "2025-05-25",
    language: "English",
  },
  {
    id: 32,
    name: "Jack Carter",
    university: "LSE",
    country: "UK",
    duration: 6,
    cost: 55000,
    deadline: "2025-07-30",
    language: "English",
  },
  {
    id: 33,
    name: "Isabella Harris",
    university: "University of Lisbon",
    country: "Portugal",
    duration: 2,
    cost: 10000,
    deadline: "2025-11-10",
    language: "English",
  },
  {
    id: 34,
    name: "Aiden Lopez",
    university: "University of Granada",
    country: "Spain",
    duration: 3,
    cost: 18000,
    deadline: "2025-03-05",
    language: "English",
  },
  {
    id: 35,
    name: "Victoria Edwards",
    university: "University of Warsaw",
    country: "Poland",
    duration: 4,
    cost: 12000,
    deadline: "2025-10-05",
    language: "English",
  },
  {
    id: 36,
    name: "Matthew Jenkins",
    university: "University of Bologna",
    country: "Italy",
    duration: 6,
    cost: 27000,
    deadline: "2025-12-15",
    language: "English",
  },
  {
    id: 37,
    name: "Aubrey Richardson",
    university: "University of Oslo",
    country: "Norway",
    duration: 3,
    cost: 30000,
    deadline: "2025-08-20",
    language: "English",
  },
  {
    id: 38,
    name: "David Fisher",
    university: "Bogazici University",
    country: "Turkey",
    duration: 5,
    cost: 16000,
    deadline: "2025-06-18",
    language: "Turkish",
  },
  {
    id: 39,
    name: "Hazel Morales",
    university: "University of Lyon",
    country: "France",
    duration: 2,
    cost: 20000,
    deadline: "2025-09-25",
    language: "French",
  },
  {
    id: 40,
    name: "Joshua Peterson",
    university: "University of Munich",
    country: "Germany",
    duration: 5,
    cost: 25000,
    deadline: "2025-03-15",
    language: "English",
  },
  {
    id: 41,
    name: "Zoe Cox",
    university: "University of California, Berkeley",
    country: "USA",
    duration: 4,
    cost: 65000,
    deadline: "2025-05-05",
    language: "English",
  },
  {
    id: 42,
    name: "Jackson Rivera",
    university: "Humboldt University of Berlin",
    country: "Germany",
    duration: 6,
    cost: 24000,
    deadline: "2025-07-10",
    language: "English",
  },
  {
    id: 43,
    name: "Layla Griffin",
    university: "Boğaziçi University",
    country: "Turkey",
    duration: 3,
    cost: 18000,
    deadline: "2025-06-01",
    language: "Turkish",
  },
  {
    id: 44,
    name: "Elijah Bell",
    university: "University of Heidelberg",
    country: "Germany",
    duration: 5,
    cost: 22000,
    deadline: "2025-08-12",
    language: "English",
  },
  {
    id: 45,
    name: "Avery Foster",
    university: "Technical University of Berlin",
    country: "Germany",
    duration: 4,
    cost: 19000,
    deadline: "2025-09-15",
    language: "English",
  },
  {
    id: 46,
    name: "Grace Ramirez",
    university: "University of Copenhagen",
    country: "Denmark",
    duration: 6,
    cost: 28000,
    deadline: "2025-03-25",
    language: "English",
  },
  {
    id: 47,
    name: "Mason Torres",
    university: "Sabancı University",
    country: "Turkey",
    duration: 3,
    cost: 16000,
    deadline: "2025-07-15",
    language: "Turkish",
  },
  {
    id: 48,
    name: "Sophie Cox",
    university: "University of British Columbia",
    country: "Canada",
    duration: 5,
    cost: 54000,
    deadline: "2025-10-30",
    language: "English",
  },
  {
    id: 49,
    name: "Carter Brooks",
    university: "University of Leuven",
    country: "Belgium",
    duration: 3,
    cost: 18000,
    deadline: "2025-04-22",
    language: "English",
  },
  {
    id: 50,
    name: "Chloe Mitchell",
    university: "University of Cambridge",
    country: "UK",
    duration: 4,
    cost: 40000,
    deadline: "2025-06-12",
    language: "English",
  },
];
